export const letters =
  "AAAAAAAAAAAAABCCCCCDDDDDDEEEEEEEEEEEEEEFGHIIIIIIJKLLLLLMMMNNNNNNNÑOOOOOOOOOPPPQRRRRRRRSSSSSSSSTTTTTUUUUVWXYZ";
export const damages: Record<string, number> = {
  A: 1,
  B: 8,
  C: 4,
  D: 2,
  E: 1,
  F: 16,
  G: 16,
  H: 16,
  I: 2,
  J: 32,
  K: 64,
  L: 4,
  M: 4,
  N: 2,
  Ñ: 64,
  O: 2,
  P: 4,
  Q: 16,
  R: 2,
  S: 2,
  T: 4,
  U: 4,
  V: 16,
  W: 120,
  X: 64,
  Y: 16,
  Z: 32,
};

export const grid: string[][] = [
  [" ", " ", " ", " ", " ", " "],
  [" ", " ", " ", " ", " ", " "],
  [" ", " ", " ", " ", " ", " "],
  [" ", " ", " ", " ", " ", " "],
  [" ", " ", " ", " ", " ", " "],
  [" ", " ", " ", " ", " ", " "],
];
